
package servicios;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_os_WS_ConsultasDocCxCService", targetNamespace = "http://suramericana.servicioscompartidos.contabilidad.cxc", wsdlLocation = "http://qassurasappi:50000/dir/wsdl?p=ic/1326910af5b63cba93a6b85b055020b4")
public class SIOsWSConsultasDocCxCService
    extends Service
{

    private final static URL SIOSWSCONSULTASDOCCXCSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIOSWSCONSULTASDOCCXCSERVICE_EXCEPTION;
    private final static QName SIOSWSCONSULTASDOCCXCSERVICE_QNAME = new QName("http://suramericana.servicioscompartidos.contabilidad.cxc", "SI_os_WS_ConsultasDocCxCService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://qassurasappi:50000/dir/wsdl?p=ic/1326910af5b63cba93a6b85b055020b4");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIOSWSCONSULTASDOCCXCSERVICE_WSDL_LOCATION = url;
        SIOSWSCONSULTASDOCCXCSERVICE_EXCEPTION = e;
    }

    public SIOsWSConsultasDocCxCService() {
        super(__getWsdlLocation(), SIOSWSCONSULTASDOCCXCSERVICE_QNAME);
    }

    public SIOsWSConsultasDocCxCService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIOSWSCONSULTASDOCCXCSERVICE_QNAME, features);
    }

    public SIOsWSConsultasDocCxCService(URL wsdlLocation) {
        super(wsdlLocation, SIOSWSCONSULTASDOCCXCSERVICE_QNAME);
    }

    public SIOsWSConsultasDocCxCService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIOSWSCONSULTASDOCCXCSERVICE_QNAME, features);
    }

    public SIOsWSConsultasDocCxCService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIOsWSConsultasDocCxCService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIOsWSConsultasDocCxC
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIOsWSConsultasDocCxC getHTTPPort() {
        return super.getPort(new QName("http://suramericana.servicioscompartidos.contabilidad.cxc", "HTTP_Port"), SIOsWSConsultasDocCxC.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIOsWSConsultasDocCxC
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIOsWSConsultasDocCxC getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://suramericana.servicioscompartidos.contabilidad.cxc", "HTTP_Port"), SIOsWSConsultasDocCxC.class, features);
    }

    /**
     * 
     * @return
     *     returns SIOsWSConsultasDocCxC
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIOsWSConsultasDocCxC getHTTPSPort() {
        return super.getPort(new QName("http://suramericana.servicioscompartidos.contabilidad.cxc", "HTTPS_Port"), SIOsWSConsultasDocCxC.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIOsWSConsultasDocCxC
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIOsWSConsultasDocCxC getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://suramericana.servicioscompartidos.contabilidad.cxc", "HTTPS_Port"), SIOsWSConsultasDocCxC.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIOSWSCONSULTASDOCCXCSERVICE_EXCEPTION!= null) {
            throw SIOSWSCONSULTASDOCCXCSERVICE_EXCEPTION;
        }
        return SIOSWSCONSULTASDOCCXCSERVICE_WSDL_LOCATION;
    }

}
