
package servicios;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_os_WS_ConsultasDocCxC", targetNamespace = "http://suramericana.servicioscompartidos.contabilidad.cxc")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SIOsWSConsultasDocCxC {


    /**
     * 
     * @param mtNegConsultasDocCxCReq
     * @return
     *     returns servicios.DTNegConsultasDocCxCRes
     * @throws P2ApplicationException
     */
    @WebMethod(operationName = "SI_os_WS_ConsultasDocCxC", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_NegConsultasDocCxCRes", targetNamespace = "http://suramericana.servicioscompartidos.contabilidad.cxc", partName = "MT_NegConsultasDocCxCRes")
    public DTNegConsultasDocCxCRes siOsWSConsultasDocCxC(
        @WebParam(name = "MT_NegConsultasDocCxCReq", targetNamespace = "http://suramericana.servicioscompartidos.contabilidad.cxc", partName = "MT_NegConsultasDocCxCReq")
        DTNegConsultasDocCxCReq mtNegConsultasDocCxCReq)
        throws P2ApplicationException
    ;

}
